FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .
RUN npx prisma generate --schema=./src/models/schema.prisma

ENV NODE_ENV=development
EXPOSE 3001

CMD ["npm", "run", "dev"]
